In [450]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Dataset 1: Student Behaviour

In [451]:
df= pd.read_csv('datasets/Student_Behaviour.csv')
df.sample(10)

,Certification Course,Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,willingness to pursue a career based on their degree,social medai & video,Travelling Time,Stress Level,Financial Status,part-time job
110,Yes,Male,BCA,154.0,50.0,86.0,68.0,70.0,Sports,30 - 60 minute,Anytime,20000,Yes,100%,1 - 1.30 hour,1 - 1.30 hour,Good,Bad,Yes
170,Yes,Female,Commerce,150.0,42.0,70.0,71.0,91.0,Sports,1 - 2 Hour,Anytime,20000,Yes,75%,30 - 60 Minute,0 - 30 minutes,Good,Fabulous,No
204,Yes,Male,Commerce,165.0,60.0,55.0,50.0,60.0,Sports,0 - 30 minute,Morning,13000,Yes,50%,1 - 30 Minute,1 - 1.30 hour,Good,Bad,No
171,Yes,Male,Commerce,178.0,60.0,70.0,60.0,60.0,Sports,2 - 3 hour,Morning,25000,Yes,50%,1 - 30 Minute,30 - 60 minutes,Good,Bad,Yes
49,No,Male,B.com Accounting and Finance,155.0,55.0,73.0,72.0,1.0,Reading books,1 - 2 Hour,Night,15000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Good,good,No
19,Yes,Female,BCA,109.0,42.0,60.0,70.0,88.0,Cinema,30 - 60 minute,Anytime,20000,Yes,100%,1 - 30 Minute,30 - 60 minutes,Good,good,No
47,No,Male,B.com Accounting and Finance,90.0,83.0,60.0,82.0,65.0,Video Games,0 - 30 minute,Anytime,100000,Yes,75%,30 - 60 Minute,1.30 - 2 hour,Awful,good,No
145,Yes,Male,B.com Accounting and Finance,170.0,80.0,75.0,90.0,85.0,Sports,More Than 4 hour,Anytime,100000,Yes,100%,30 - 60 Minute,1.30 - 2 hour,fabulous,Bad,No
5,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,0 - 30 minutes,Bad,good,No
111,Yes,Female,BCA,172.0,49.0,94.0,69.0,85.0,Cinema,30 - 60 minute,Anytime,12000,Yes,50%,30 - 60 Minute,2 - 2.30 hour,Bad,good,No

In [452]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.lower() 
df.rename(columns={
    'social_medai_&_video': 'social_media_usage',
    'daily_studing_time': 'study_time',
    'college_mark': 'college_marks'
}, inplace=True)
df.sample(10)

,certification_course,gender,department,height(cm),weight(kg),10th_mark,12th_mark,college_marks,hobbies,study_time,prefer_to_study_in,salary_expectation,do_you_like_your_degree?,willingness_to_pursue_a_career_based_on_their_degree,social_media_usage,travelling_time,stress_level,financial_status,part-time_job
146,No,Male,BCA,165.0,45.0,50.0,50.0,65.0,Cinema,0 - 30 minute,Night,15000,Yes,25%,1 - 30 Minute,0 - 30 minutes,fabulous,Fabulous,Yes
66,Yes,Female,BCA,160.0,42.0,80.0,75.0,75.0,Reading books,2 - 3 hour,Morning,20000,Yes,75%,1 - 30 Minute,1 - 1.30 hour,Good,good,No
102,Yes,Female,BCA,162.0,65.0,95.0,85.0,86.0,Reading books,1 - 2 Hour,Night,15000,Yes,50%,1.30 - 2 hour,30 - 60 minutes,Good,good,No
77,Yes,Male,BCA,172.0,91.0,92.0,69.0,85.0,Cinema,1 - 2 Hour,Night,15000,Yes,75%,1 - 1.30 hour,1 - 1.30 hour,Good,good,No
188,Yes,Male,B.com ISM,170.0,80.0,67.0,70.0,60.0,Sports,More Than 4 hour,Anytime,700000,Yes,100%,1 - 30 Minute,0 - 30 minutes,Good,good,No
197,Yes,Male,B.com ISM,153.0,45.0,67.0,54.0,86.0,Cinema,30 - 60 minute,Morning,30000,Yes,100%,1 - 30 Minute,30 - 60 minutes,Good,good,No
55,No,Male,Commerce,100.0,47.0,87.0,84.0,92.0,Sports,30 - 60 minute,Morning,20000,Yes,75%,1 - 1.30 hour,30 - 60 minutes,fabulous,Bad,No
80,No,Female,BCA,155.0,52.0,7.4,79.0,75.0,Sports,1 - 2 Hour,Night,12000,Yes,75%,1.30 - 2 hour,30 - 60 minutes,Good,Bad,No
99,No,Male,BCA,180.0,67.0,80.0,70.0,60.0,Video Games,0 - 30 minute,Anytime,10000,Yes,25%,1 - 30 Minute,0 - 30 minutes,Good,good,No
210,Yes,Female,Commerce,152.0,32.0,80.0,60.0,70.0,Sports,1 - 2 Hour,Night,15,Yes,75%,1 - 1.30 hour,30 - 60 minutes,Bad,good,No

In [453]:
df.isnull().sum()

certification_course                                    0
gender                                                  0
department                                              0
height(cm)                                              0
weight(kg)                                              0
10th_mark                                               0
12th_mark                                               0
college_marks                                           0
hobbies                                                 0
study_time                                              0
prefer_to_study_in                                      0
salary_expectation                                      0
do_you_like_your_degree?                                0
willingness_to_pursue_a_career_based_on_their_degree    0
social_media_usage                                      0
travelling_time                                         0
stress_level                                            0
financial_status                                        0
part-time_job                                           0
dtype: int64

In [454]:
binary_cols=[
    'certification_course',
    'do_you_like_your_degree?',
    'part-time_job'
]
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [455]:
df['financial_status'].unique()

array(['Bad', 'good', 'Awful', 'Fabulous'], dtype=object)

In [456]:
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})
df['financial_status'] = df['financial_status'].map({
    'Fabulous':2,
    'good':4,
    'Bad':7,
    'Awful':9
})

In [457]:
df['study_time'].unique()

array(['0 - 30 minute', '30 - 60 minute', '1 - 2 Hour', '2 - 3 hour',
       '3 - 4 hour', 'More Than 4 hour'], dtype=object)

In [458]:
df['study_time']=df['study_time'].map({
    '0 - 30 minute':0.25,
    '30 - 60 minute':0.75,
    '1 - 2 Hour':1.5,
    '2 - 3 hour':2.5,
    '3 - 4 hour':3.5,
    'More Than 4 hour':5
})

In [459]:
df['stress_level'].unique()

array(['Bad', 'Awful', 'Good', 'fabulous'], dtype=object)

In [460]:
df['stress_level']=df['stress_level'].map({
    'fabulous':2,
    'Good':4,
    'Bad':7,
    'Awful':9
})

In [461]:
df['social_media_usage'].unique()

array(['1.30 - 2 hour', '1 - 1.30 hour', 'More than 2 hour',
       '30 - 60 Minute', '1 - 30 Minute', '0 Minute'], dtype=object)

In [462]:
df['social_media_usage'] = df['social_media_usage'].map({
    '1.30 - 2 hour': 1.75,
    '1 - 1.30 hour': 1.25,
    'More than 2 hour': 3,
    '30 - 60 Minute': 0.75,
    '1 - 30 Minute': 0.5,
    '0 Minute': 0
})

In [463]:
df['travelling_time'].unique()

array(['30 - 60 minutes', '0 - 30 minutes', '1 - 1.30 hour',
       '2 - 2.30 hour', '1.30 - 2 hour', 'more than 3 hour',
       '2.30 - 3 hour'], dtype=object)

In [464]:
df['travelling_time'] = df['travelling_time'].str.lower().map({
    '30 - 60 minutes': 0.45,
    '0 - 30 minutes': 0.15,
    '1 - 1.30 hour': 1.15,
    '2 - 2.30 hour':2.15,
    '1.30 - 2 hour':1.45,
    '2.30 - 3 hour':2.5,
    'more than 3 hour': 3.5
})

In [465]:
df['willingness_to_pursue_a_career_based_on_their_degree'].unique()

array(['50%', '75%', '25%', '100%', '0%'], dtype=object)

In [466]:
df['career_alignment'] = df['willingness_to_pursue_a_career_based_on_their_degree'].str.replace('%', '').astype(int)
df['career_alignment'] = df['career_alignment'] / 100

In [467]:
df.drop([
    'height(cm)',
    'weight(kg)',
    'hobbies',
    'salary_expectation',
    'prefer_to_study_in',
    'department',
    'willingness_to_pursue_a_career_based_on_their_degree'
], axis=1, inplace=True)

In [468]:
# New column: Academic pressure
df['academic_pressure'] = (
    df['study_time'] * (100 - df['college_marks'])
)

# New column: Lifestyle stress
df['lifestyle_stress'] = (
    df['social_media_usage'] + df['travelling_time']
)

In [469]:
df.drop([
    '10th_mark',
    '12th_mark',
    'certification_course'
], axis=1, inplace=True)

In [470]:
df.sample(10)

,gender,college_marks,study_time,do_you_like_your_degree?,social_media_usage,travelling_time,stress_level,financial_status,part-time_job,career_alignment,academic_pressure,lifestyle_stress
191,0,89.0,0.75,1,1.25,1.15,4,4,0,0.50,8.25,2.40
114,0,80.0,1.50,0,0.75,1.45,7,9,1,0.50,30.00,2.20
202,1,80.0,3.50,1,1.75,0.15,4,4,0,0.75,70.00,1.90
146,0,65.0,0.25,1,0.50,0.15,2,2,1,0.25,8.75,0.65
212,1,80.0,1.50,1,0.75,1.15,4,4,0,0.75,30.00,1.90
48,0,60.0,1.50,1,0.75,0.45,2,4,0,0.50,60.00,1.20
152,0,60.0,0.75,1,0.75,1.15,9,4,0,0.50,30.00,1.90
137,0,80.0,5.00,0,0.75,1.15,4,7,0,0.75,100.00,1.90
217,1,75.0,0.25,1,3.00,0.15,9,4,0,0.75,6.25,3.15
80,1,75.0,1.50,1,1.75,0.45,4,7,0,0.75,37.50,2.20

# Dataset 2: Stress Factors

In [471]:
df1=pd.read_csv('datasets/Stress_Factor.csv')
df1.sample(10)

,Kindly Rate your Sleep Quality 😴,How many times a week do you suffer headaches 🤕?,How would you rate you academic performance 👩‍🎓?,how would you rate your study load?,How many times a week you practice extracurricular activities 🎾?,How would you rate your stress levels?
77,3,2,3,4,1,5
374,4,3,3,4,2,2
145,4,1,4,5,1,5
62,4,3,3,4,2,2
272,4,3,2,2,4,1
398,2,3,3,2,5,2
433,1,1,1,1,1,2
98,3,2,3,5,4,3
440,5,1,4,2,1,1
91,3,2,3,1,1,5

In [472]:
df1.isnull().sum()

Kindly Rate your Sleep Quality 😴                                    0
How many times a week do you suffer headaches 🤕?                    0
How would you rate you academic performance 👩‍🎓?                    0
how would you rate your study load?                                 0
How many times a week you practice extracurricular activities 🎾?    0
How would you rate your stress levels?                              0
dtype: int64

In [473]:
df.columns = df.columns.str.strip().str.lower()

In [474]:
df1.rename(columns={
    'Kindly Rate your Sleep Quality 😴': 'sleep_quality',
    'How many times a week do you suffer headaches 🤕?': 'headache_freq',
    'How would you rate you academic performance 👩‍🎓?': 'academic_performance',
    'how would you rate your study load?': 'study_load',
    'How many times a week you practice extracurricular activities 🎾?': 'extracurricular_freq',
    'How would you rate your stress levels?': 'stress_level'
}, inplace=True)
df1.sample(10)

,sleep_quality,headache_freq,academic_performance,study_load,extracurricular_freq,stress_level
123,2,3,3,2,3,4
469,3,1,4,3,1,3
58,5,2,4,4,4,2
21,3,3,4,4,3,3
109,3,1,3,2,1,1
98,3,2,3,5,4,3
7,4,3,1,4,1,1
490,3,5,3,2,3,5
167,3,4,3,5,5,5
274,3,3,5,3,4,1

In [475]:
df1['sleep_quality'].unique()

array([3, 4, 2, 1, 5])

In [476]:
scaler = MinMaxScaler()
cols = [
    'sleep_quality',
    'headache_freq',
    'academic_performance',
    'study_load',
    'extracurricular_freq',
    'stress_level'
]

df1[cols] = scaler.fit_transform(df1[cols])

In [477]:
df1.sample(10)

,sleep_quality,headache_freq,academic_performance,study_load,extracurricular_freq,stress_level
202,0.50,0.25,0.50,1.00,0.75,0.50
484,0.25,1.00,0.25,0.00,0.25,0.00
360,0.50,0.50,0.75,0.75,0.75,0.50
192,0.50,0.25,0.75,1.00,0.00,1.00
5,0.50,0.00,0.50,0.25,0.00,0.00
517,0.25,0.50,1.00,0.00,1.00,0.25
431,0.25,0.50,0.50,1.00,0.50,0.75
373,0.50,0.25,1.00,0.75,0.25,0.75
185,0.50,0.00,0.50,0.00,0.25,0.25
189,0.75,0.25,0.50,0.50,0.00,0.75

In [478]:
df1['mental_strain'] = (df1['stress_level'] + df1['study_load'] + df1['headache_freq'])
df1['recovery_score']=df1['sleep_quality']+df1['extracurricular_freq']
df1['performance_pressure']=(df1['study_load']*(1-df1['academic_performance']))

In [479]:
df1['burnout_score'] = (0.4 * df1['mental_strain'] +0.3 * (1 - df1['recovery_score']) +0.3 * df1['performance_pressure'])
df1['burnout_level'] = pd.qcut(
    df1['burnout_score'],
    q=3,
    labels=['Low', 'Medium', 'High']
)

# Dataset 3: Student Mental Health

In [480]:
df2=pd.read_csv('datasets/Student_Mental_Health.csv')
df2.sample(10)

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
943,Diya,Female,19,Class 12,6.3,8.8,7.4,High,Yes,Same
42,Aadhya,Female,16,Class 9,7.8,6.9,2.0,Low,Yes,Same
357,Ishaan,Male,21,BSc,4.4,6.3,2.6,Medium,No,Declined
373,Arjun,Male,18,Class 11,2.6,5.8,3.5,Medium,No,Improved
477,Ishaan,Male,15,Class 9,7.2,8.2,3.6,Medium,Yes,Improved
67,Riya,Female,15,Class 8,3.1,5.6,6.0,Low,No,Same
605,Reyansh,Male,15,Class 9,9.5,4.9,9.5,High,Yes,Improved
786,Reyansh,Male,17,Class 10,10.6,7.9,3.7,High,Yes,Same
643,Aarav,Male,25,MA,5.0,5.2,9.5,Medium,No,Improved
873,Reyansh,Male,24,MTech,8.8,8.0,8.0,Medium,No,Declined

In [481]:
df2.isnull().sum()

Name                            0
Gender                          0
Age                             0
Education Level                 0
Screen Time (hrs/day)           0
Sleep Duration (hrs)            0
Physical Activity (hrs/week)    0
Stress Level                    0
Anxious Before Exams            0
Academic Performance Change     0
dtype: int64

In [482]:
df2.columns = df2.columns.str.strip().str.lower().str.replace(' ', '_')

df2.rename(columns={
    'Screen Time (hrs/day)': 'screen_time',
    'Sleep Duration (hrs)': 'sleep_hours',
    'Physical Activity (hrs/week)': 'physical_activity',
    'Stress Level': 'stress_level',
    'anxious before exams': 'exam_anxiety',
    'Academic Performance Change': 'performance_change'
}, inplace=True)
df2.sample(10)

,name,gender,age,education_level,screen_time_(hrs/day),sleep_duration_(hrs),physical_activity_(hrs/week),stress_level,anxious_before_exams,academic_performance_change
351,Vihaan,Male,15,Class 8,8.4,5.8,0.6,Low,Yes,Improved
277,Aarav,Male,24,MA,9.5,8.9,8.0,Low,Yes,Same
840,Krishna,Male,23,MTech,11.7,4.2,4.0,Low,Yes,Same
176,Anika,Female,15,Class 8,8.8,7.5,9.9,Low,No,Improved
807,Shaurya,Male,24,MSc,9.0,7.2,0.6,Medium,No,Same
919,Ishaan,Male,25,MTech,3.3,6.4,4.2,Medium,No,Improved
844,Anika,Female,20,BA,5.0,4.3,7.7,Low,Yes,Declined
187,Vivaan,Male,18,Class 12,4.5,5.7,2.8,Low,No,Improved
568,Sai,Male,16,Class 10,7.8,6.3,1.6,Medium,Yes,Declined
749,Ananya,Female,24,MSc,8.1,4.6,2.2,High,Yes,Same

In [483]:
df2.drop(['name'], axis=1, inplace=True)
df2['gender'] = df2['gender'].map({'Male': 0,'Female': 1})

In [484]:
df2['education_level'].unique()

array(['Class 8', 'MSc', 'BTech', 'BA', 'Class 11', 'MTech', 'Class 9',
       'Class 10', 'MA', 'BSc', 'Class 12'], dtype=object)

In [485]:
df2['education_level'] = df2['education_level'].map({
    'Class 8': 1,
    'Class 9': 2,
    'Class 10': 3,
    'Class 11': 4,
    'Class 12': 5,
    'BA': 6,
    'BSc': 6,
    'BTech': 6,
    'MA': 7,
    'MSc': 7,
    'MTech': 7
})

In [486]:
df2['screen_time_(hrs/day)'].unique()

array([ 7.1,  3.3,  9.5, 10.8,  2.8,  8.6,  3.6,  7. ,  4.8,  8.9,  8. ,
       10.3,  5.8, 11.2, 11.1, 11.5,  9.7,  2.5,  6.9,  6. ,  7.6, 11. ,
        3. ,  4.7,  9.9,  3.2,  7.9,  5.4,  2.4, 11.4, 10.6, 11.7,  6.7,
        8.3,  6.6,  5.6,  7.8, 11.9,  9.4,  9.3,  5.1,  7.2, 10.7,  4.9,
        3.1,  8.7,  6.1,  3.4,  2.2,  7.3,  7.7, 10. ,  4.1,  3.5,  2.6,
        9.8,  9.1,  7.5,  3.9, 10.5,  4.6,  6.4,  5.2,  2.3,  3.7,  8.1,
        4.3, 11.8,  9.2,  5.9,  4.2,  4.5, 10.1,  6.3,  9.6,  5.3, 11.6,
        7.4,  2.9,  8.8,  8.4,  3.8,  2.7,  8.5,  4.4, 12. ,  8.2,  4. ,
        6.2, 10.2,  5.5,  5. ,  9. ,  2. , 10.4,  2.1, 10.9,  5.7,  6.5,
        6.8, 11.3])

In [487]:
cols = ['screen_time_(hrs/day)', 'sleep_duration_(hrs)', 'physical_activity_(hrs/week)']

df2[cols] = scaler.fit_transform(df2[cols])

In [488]:
df2['stress_level'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [489]:
df2['stress_level'] = df2['stress_level'].str.strip().str.lower()

In [490]:
df2['stress_level'] = df2['stress_level'].map({
    'low': 3,
    'medium': 6,
    'high': 9
})

In [491]:
df

,gender,college_marks,study_time,do_you_like_your_degree?,social_media_usage,travelling_time,stress_level,financial_status,part-time_job,career_alignment,academic_pressure,lifestyle_stress
0,0,80.0,0.25,0,1.75,0.45,7,7,0,0.50,5.00,2.20
1,1,70.0,0.75,1,1.25,0.15,7,7,0,0.75,22.50,1.40
2,0,55.0,1.50,1,3.00,0.45,9,7,0,0.50,67.50,3.45
3,1,58.0,1.50,0,1.75,0.15,7,4,0,0.50,63.00,1.90
4,0,30.0,0.75,1,1.75,0.45,4,4,0,0.25,52.50,2.20
...,...,...,...,...,...,...,...,...,...,...,...,...
230,0,65.0,0.75,1,3.00,0.45,7,7,0,0.50,26.25,3.45
231,0,76.0,2.50,1,0.75,0.45,4,4,0,0.75,60.00,1.20
232,1,70.0,0.75,1,0.75,2.50,7,4,0,0.50,22.50,3.25
233,1,75.0,0.25,1,3.00,2.50,9,4,0,0.75,6.25,5.50
234,1,50.0,3.50,0,0.75,2.50,2,4,0,0.75,175.00,3.25

In [492]:
df2['anxious_before_exams'] = df2['anxious_before_exams'].map({
    'Yes': 1,
    'No': 0
})

In [493]:
df2['academic_performance_change'].unique()

array(['Same', 'Improved', 'Declined'], dtype=object)

In [494]:
df2['academic_performance_change'] = df2['academic_performance_change'].map({
    'Improved': 1,
    'Same': 0,
    'Declined': -1
})

In [495]:
df2['lifestyle_stress'] = (
    df2['screen_time_(hrs/day)'] + 
    (10 - df2['sleep_duration_(hrs)'])
)

In [496]:
df2['health_balance'] = (
    df2['physical_activity_(hrs/week)'] - df2['screen_time_(hrs/day)']
)

In [497]:
df2['anxiety_impact'] = (
    df2['anxious_before_exams'] * df2['stress_level']
)

In [498]:
df.shape

(235, 12)

In [499]:
df1.shape

(520, 11)

In [500]:
df2.shape

(1000, 12)

# Final Dataset:

### Combining all three datasets

In [501]:
n=1000
data = pd.DataFrame()

In [502]:
data['study_time'] = df['study_time'].sample(n, replace=True).values
data['social_media_usage'] = df['social_media_usage'].sample(n, replace=True).values

In [503]:
data['sleep_quality'] = df1['sleep_quality'].sample(n, replace=True).values
data['headache_freq'] = df1['headache_freq'].sample(n, replace=True).values
data['study_load'] = df1['study_load'].sample(n, replace=True).values
data['extracurricular_freq'] = df1['extracurricular_freq'].sample(n, replace=True).values

In [504]:
data['screen_time'] = df2['screen_time_(hrs/day)'].sample(n, replace=True).values
data['sleep_hours'] = df2['sleep_duration_(hrs)'].sample(n, replace=True).values
data['physical_activity'] = df2['physical_activity_(hrs/week)'].sample(n, replace=True).values
data['exam_anxiety'] = df2['anxious_before_exams'].sample(n, replace=True).values

In [505]:
combined_stress = pd.concat([
    df['stress_level'],
    df1['stress_level'],
    df2['stress_level']
])
data['stress_level'] = combined_stress.sample(n, replace=True).values
data['stress_level'] = (
    data['stress_level'] + (1 - data['sleep_hours'])
) / 2

In [506]:
data.sample(20)

,study_time,social_media_usage,sleep_quality,headache_freq,study_load,extracurricular_freq,screen_time,sleep_hours,physical_activity,exam_anxiety,stress_level
641,0.75,1.25,1.00,0.50,0.75,0.25,0.63,0.42,0.73,0,0.415
176,1.50,0.75,0.50,0.00,0.75,0.50,0.90,0.34,0.48,0,3.330
978,0.25,1.25,0.50,0.75,0.75,0.50,0.69,0.22,0.68,1,3.390
617,0.75,0.75,0.50,0.00,0.75,0.25,0.99,0.68,0.85,1,0.285
412,1.50,1.75,0.25,0.00,0.50,0.25,0.86,0.06,0.58,1,4.970
204,0.75,3.00,0.50,0.00,0.00,0.00,0.37,0.16,0.63,0,0.795
526,0.25,1.25,0.50,0.50,0.25,1.00,0.90,0.14,0.66,0,0.930
426,1.50,1.25,0.25,0.00,0.00,0.50,0.70,0.40,0.21,1,3.300
315,0.75,0.75,0.00,0.50,1.00,0.25,0.32,0.08,0.67,1,0.710
945,0.25,1.25,0.50,0.00,0.50,1.00,0.91,0.18,0.75,1,4.910
684,0.75,1.25,0.50,0.25,0.25,0.50,0.51,0.62,0.63,1,3.190
970,0.75,0.75,0.00,0.50,0.75,0.00,0.60,0.00,0.86,1,4.000
974,2.50,0.75,0.50,0.00,0.00,1.00,0.06,0.74,0.35,1,0.130
812,1.50,3.00,0.50,0.00,0.25,1.00,0.95,0.24,0.85,0,1.880
638,0.25,0.75,0.50,0.50,0.00,0.00,0.71,0.52,0.95,1,0.365
540,0.25,3.00,0.50,0.00,0.50,0.00,0.01,0.60,0.67,0,3.700
979,1.50,1.75,0.00,0.00,0.75,0.50,0.35,0.58,0.03,1,3.710
650,1.50,0.50,1.00,0.75,0.25,0.50,0.62,0.20,0.90,0,1.900
845,2.50,0.50,0.50,1.00,0.75,0.00,0.02,0.38,0.76,0,3.310
779,0.25,0.00,0.50,1.00,0.75,0.25,0.05,0.36,0.32,1,4.820

In [507]:
scaler = MinMaxScaler()

cols = [
    'study_time', 'social_media_usage',
    'sleep_quality', 'headache_freq',
    'study_load', 'extracurricular_freq',
    'screen_time', 'sleep_hours',
    'physical_activity', 'stress_level'
]

data[cols] = scaler.fit_transform(data[cols])

In [508]:
#Mental strain
data['mental_strain'] = (
    data['stress_level'] +
    data['study_load'] +
    data['headache_freq']
)

# Recovery score
data['recovery_score'] = (
    data['sleep_quality'] +
    data['extracurricular_freq']
)

# Performance pressure
data['performance_pressure'] = (
    data['study_load'] * (1 - data['study_time'])
)

# Lifestyle stress
data['lifestyle_stress'] = (
    data['screen_time'] + (1 - data['sleep_hours'])
)

In [509]:
data['burnout_score'] = (
    0.4 * data['mental_strain'] +
    0.3 * (1 - data['recovery_score']) +
    0.3 * data['performance_pressure']
)

In [510]:
data['burnout_level'] = pd.qcut(
    data['burnout_score'],
    q=3,
    labels=['Low', 'Medium', 'High']
)

In [511]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

,study_time,social_media_usage,sleep_quality,headache_freq,study_load,extracurricular_freq,screen_time,sleep_hours,physical_activity,exam_anxiety,stress_level,mental_strain,recovery_score,performance_pressure,lifestyle_stress,burnout_score,burnout_level
0,0.263158,0.250000,0.50,0.00,0.75,0.50,0.90,0.34,0.48,0,0.665331,1.415331,1.00,0.552632,1.56,0.731922,High
1,0.105263,0.416667,0.50,0.00,0.50,0.50,0.12,0.98,0.68,0,0.025050,0.525050,1.00,0.447368,0.14,0.344231,Low
2,0.000000,0.583333,0.50,0.00,0.25,0.00,0.79,0.42,0.83,1,0.131263,0.381263,0.50,0.250000,1.37,0.377505,Low
3,1.000000,0.250000,0.50,0.75,0.00,0.25,0.33,0.98,0.05,1,0.601202,1.351202,0.75,0.000000,0.35,0.615481,Medium
4,0.263158,0.250000,0.25,0.00,0.75,0.50,0.40,0.12,0.61,1,0.086172,0.836172,0.75,0.552632,1.28,0.575258,Medium

In [512]:
print(data['burnout_level'].value_counts())

burnout_level
Medium    334
Low       333
High      333
Name: count, dtype: int64

In [513]:
data.to_csv('datasets/burnout_final_dataset.csv')